### ISSUE TITLE
403 message when running

### ISSUE THREAD

**Issue by zchef2k** [shashlik/shashlik-runtime-env#3]
Why would I get a 403 on the GET /apk_file call?

Sending APK
127.0.0.1 - - [03/Mar/2016 15:57:47] "GET /apk_file HTTP/1.1" 403 -
ParseResult(scheme='', netloc='', path='/startup', params='', query='', fragment='')
127.0.0.1 - - [03/Mar/2016 15:57:47] "GET /startup HTTP/1.1" 200 -

**Comment by davidedmundson** [comment]
It means the APK has already been sent to the emulator. 

It's expected behaviour, even if it is a slightly odd use of error codes.

**Comment by zchef2k** [comment]
Got it. Its the only clue I have why it might not be displaying anything on my system.

Fedora 23 (installed from an alien rebuild of your .deb)
Plasma5
libGL 11.0.4 (symlinked from /usr/lib/libGL.so.1 to /usr/lib/libGL.so)

**Comment by davidedmundson** [comment]
what do you mean by nothing.
a big black window? or no window?
is there a back button at the bottom of the window?

**Comment by zchef2k** [comment]
The window draws with android buttons at the bottom. Otherwise black/blank.

Maybe this isn't the place to hash out my issues. Let me know if there's a more appropriate way to contribute.

**Comment by davidedmundson** [comment]
​Oh ok.

you can try wiping ~/.local/share/shashlik/userdata.img

try also re-installing the APK

then finally run "adb -e logcat" and see if that says anything. There's a
version of adb shipped with the shaslik runtime

**Comment by zchef2k** [comment]
After deleting userdata and reinstalling the app, I've got flappybird at least running (havent played it) and I understand the logging better.

Really cool, thanks.

**Comment by hendrikreuhl** [comment]
Having same issue.
No changes after deleting userdata or reinstalling
This are the last Logcat messages:

I/ActivityManager( 1154): Delay finish: com.android.providers.calendar/.CalendarProviderBroadcastReceiver
E/SQLiteLog( 1518): (284) automatic index on view_events(_id)
I/ActivityManager( 1154): Resuming delayed broadcast
I/MediaFocusControl( 1154):  AudioFocus  abandonAudioFocus() from android.media.AudioManager@17ecbef0com.android.music.MediaPlaybackService$3@2f9a9c69
I/ActivityManager( 1154): Start proc 1652:com.android.musicfx/u0a8 for broadcast com.android.musicfx/.ControlPanelReceiver
V/MusicFXControlPanelReceiver( 1652): onReceive
V/MusicFXControlPanelReceiver( 1652): Action: android.media.action.CLOSE_AUDIO_EFFECT_CONTROL_SESSION
V/MusicFXControlPanelReceiver( 1652): Package name: com.android.music
V/MusicFXControlPanelReceiver( 1652): Audio session: 4
V/MusicFXControlPanelEffect( 1652): closeSession(android.app.ReceiverRestrictedContext@ada1831, com.android.music, 4)
